### ISSUE TITLE
Error (Server Error, PreconditionFailedException) thrown during batch call

### ISSUE THREAD

**Issue by tslilyai** [Microsoft/EmbeddedSocial-Java-API-Library#23]
The first request in the issued batch was a CreateTopic request. The first response in the batch response was the below error response. This also caused parsing errors in the batch client, but PR 21 should handle that.

```
Content-Type: application/http; msgtype=response
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
{
  message: An error has occurred.,
  exceptionMessage: Precondition failed. Check for ETag conditions.,
  exceptionType: Microsoft.CTStore.PreconditionFailedException,
  stackTrace:    at Microsoft.CTStore.ExecutionManager.<ExecuteStrongConsistentTransactionAsync>d__7.MoveNext() in c:\\dev\\sp3\\code\\Server\\CTStore\\ExecutionManager.cs:line 241
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Microsoft.CTStore.ExecutionManager.<ExecuteTransactionAsync>d__5.MoveNext() in c:\\dev\\sp3\\code\\Server\\CTStore\\ExecutionManager.cs:line 91
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Microsoft.CTStore.CTStore.<ExecuteTransactionAsync>d__9.MoveNext() in c:\\dev\\sp3\\code\\Server\\CTStore\\CTStore.cs:line 111
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at SocialPlus.Server.Tables.CommentsStore.<InsertTopicComment>d__6.MoveNext() in c:\\dev\\sp3\\code\\Server\\Common\\Tables\\CommentsStore.cs:line 158
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SocialPlus.Server.Managers.CommentsManager.<CreateComment>d__4.MoveNext() in c:\\dev\\sp3\\code\\Server\\Common\\Managers\\CommentsManager.cs:line 100
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SocialPlus.Server.Controllers.TopicCommentsController.<PostComment>d__7.MoveNext() in c:\\dev\\sp3\\code\\Server\\WebRole\\Controllers\\TopicCommentsController.cs:line 121
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown 
      innerException: {
        message: An error has occurred.,
        exceptionMessage: Element 1 in the batch returned an unexpected response code.,
        exceptionType: Microsoft.WindowsAzure.Storage.StorageException,
        stackTrace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Executor\\Executor.cs:line 60   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Util\\AsyncExtensions.cs:line 66
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.CTStore.AzureTableStorage.<Execute>d__26.MoveNext() in c:\\dev\\sp3\\code\\Server\\CTStore\\AzureTableStorage.cs:line 423
        }
}
```

**Comment by ssaroiu** [comment]
Hi Lily,

Thanks for this. We definitely need to investigate this issue on our side. In the meantime, one quick remedy is to avoid setting limit to '-1' in our API calls. Just leave them unset for now.
